### ISSUE TITLE
Prune Mode Issue

### ISSUE THREAD

**Issue by Jbashimov** [Digital-Revelation/Byiness#1]
When I select prune mode blockchain size, the wallet start with the error "Prune mode incompatible with -txindex "

**Comment by le2Ks** [comment]
> When I select prune mode blockchain size, the wallet start with the error "Prune mode incompatible with -txindex "

Hello,

Add the following into your  conf file:
```txindex=0```
and restart the wallet. This will disable txindex (which is enabled by default) and will allow prune mode.

Best'

**Comment by Jbashimov** [comment]
> > When I select prune mode blockchain size, the wallet start with the error "Prune mode incompatible with -txindex "
> 
> 
> 
> Hello,
> 
> 
> 
> Add the following into your  conf file:
> 
> ```txindex=0```
> 
> and restart the wallet. This will disable txindex (which is enabled by default) and will allow prune mode.
> 
> 
> 
> Best'

Worke@ out. Thanks!
